-- Insert items
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Collar para perro', 1500);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Juguete para gato', 800);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Alimento para peces', 600);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Cama para perro', 3500);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Rascador para gato', 2500);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Correa para perro', 1200);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Jaula para hámster', 4000);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Rueda para hámster', 1000);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Shampoo para perro', 800);
INSERT INTO ITEMS (ITEM_NAME, ITEM_PRICE) VALUES ('Arenero para gato', 2000);

-- Insert orders
INSERT INTO ORDENES_DE_COMPRA (ESTADO) VALUES ('Creada');
INSERT INTO ORDENES_DE_COMPRA (ESTADO) VALUES ('Pagada');
INSERT INTO ORDENES_DE_COMPRA (ESTADO) VALUES ('Despachada');
INSERT INTO ORDENES_DE_COMPRA (ESTADO) VALUES ('Completada');
INSERT INTO ORDENES_DE_COMPRA (ESTADO) VALUES ('Anulada');

-- Associate items with orders
INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (1, 1, 1);
INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (1, 2, 2);

INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (2, 3, 1);
INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (2, 4, 1);
INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (2, 5, 1);

INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (3, 6, 1);

INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (4, 7, 1);
INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (4, 8, 1);

INSERT INTO ORDEN_ITEMS (ORDEN_ID, ITEM_ID, QUANTITY) VALUES (5, 9, 1);